name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 🍏 macOS (Clang - Debug)
            os: macos-latest
            platform: macos
            build_type: Debug
          - name: 🍏 macOS (Clang - Release)
            os: macos-latest
            platform: macos
            build_type: Release

          - name: 🐧 Linux (GCC - Debug)
            os: ubuntu-latest
            platform: linux
            build_type: Debug
          - name: 🐧 Linux (GCC - Release)
            os: ubuntu-latest
            platform: linux
            build_type: Release

          - name: 🪟 Windows (MSVC - Debug)
            os: windows-latest
            platform: windows
            arch: x86_64
            build_type: Debug
          - name: 🪟 Windows (MSVC - Release)
            os: windows-latest
            platform: windows
            arch: x86_64
            build_type: Release

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure MSVC console (Windows)
        if: matrix.platform == 'windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build
        run: make

      - name: Test
        run: ./test.sh
